/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Praticien;
import Controller.MysqlConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

//import Model.dao.DaoPraticien;
//import Model.dao.DaoException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elise
 */
public final class PraticienView extends javax.swing.JFrame {

    /**
     * Creates new form PraticienView
     */
    public PraticienView() {
        initComponents();
        Show_Praticien_In_JTable();
        Show_Combo1_Praticien();
        //selectAll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        praticienTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonOk = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();
        jButtonAjout = new javax.swing.JButton();
        jButtonPrec = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("LISTE DES PRATICIENS");

        praticienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Adresse du cabinet", "Ville", "Code Postal", "Secteur", "Téléphone"
            }
        ));
        jScrollPane1.setViewportView(praticienTable);

        jLabel2.setText("Rechercher Praticien:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonFermer.setText("Fermer");

        jButtonAjout.setText("Ajouter");
        jButtonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutActionPerformed(evt);
            }
        });

        jButtonPrec.setText("Précédent");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPrec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addComponent(jButtonFermer)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonOk)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOk)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrec)
                    .addComponent(jButtonAjout)
                    .addComponent(jButtonFermer))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutActionPerformed
    }//GEN-LAST:event_jButtonAjoutActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        //nomDesc = (String).getSelectedItem();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     *
     * @return
     */
    public ArrayList<Praticien> getPraticienList() {
        ArrayList<Praticien> praticienList = new ArrayList<Praticien>();
        Connection connection = MysqlConnection.ConnectDB();

        String query = "SELECT * FROM  praticien ";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Praticien praticien;
            while (rs.next()) {
                praticien = new Praticien(rs.getString("nom"), rs.getString("prenom"), rs.getString("adresse"), rs.getString("ville"), rs.getString("code_postal"), rs.getString("secteur"), rs.getString("telephone"));
                praticienList.add(praticien);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return praticienList;
    }

    // Table triée en fonction du Nom
    /**
     *
     * @return
     */
    public ArrayList<Praticien> select_NomByDesc() {
        ArrayList<Praticien> praticienList = new ArrayList<Praticien>();
        Connection connection = MysqlConnection.ConnectDB();

        String query = "SELECT * FROM  praticien ORDER BY nom DESC ";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Praticien praticien;
            while (rs.next()) {
                praticien = new Praticien(rs.getString("nom"), rs.getString("prenom"), rs.getString("adresse"), rs.getString("ville"), rs.getString("code_postal"), rs.getString("secteur"), rs.getString("telephone"));
                praticienList.add(praticien);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return praticienList;
    }

    // Table triée en fonction de la date de visite
    /**
     *
     * @return
     */
    public ArrayList<Praticien> select_GroupByDate() {
        ArrayList<Praticien> praticienList = new ArrayList<Praticien>();
        Connection connection = MysqlConnection.ConnectDB();

        String query = "SELECT p.nom, p.prenom, r.date FROM  praticien, rapportdevisite AS p, r  GROUP BY Date_visite ";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Praticien praticien;
            while (rs.next()) {
                praticien = new Praticien(rs.getString("nom"), rs.getString("prenom"), rs.getString("adresse"), rs.getString("ville"), rs.getString("code_postal"), rs.getString("secteur"), rs.getString("telephone"));
                praticienList.add(praticien);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return praticienList;
    }
//

    /**
     *
     */
    public void Show_Praticien_In_JTable() {
        ArrayList<Praticien> list = getPraticienList();
        DefaultTableModel model = (DefaultTableModel) praticienTable.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNom();
            row[1] = list.get(i).getPrenom();
            row[2] = list.get(i).getAdresse();
            row[3] = list.get(i).getVille();
            row[4] = list.get(i).getCode_postal();
            row[5] = list.get(i).getSecteur();
            row[6] = list.get(i).getTelephone();
            model.addRow(row);
        }
    }

    /**
     *
     * @param query
     * @param message
     */
    public void executeSQlQuery(String query, String message) {
        Connection con = MysqlConnection.ConnectDB();
        Statement st;
        try {
            st = con.createStatement();
            if ((st.executeUpdate(query)) == 1) {
                // refresh jtable data
                DefaultTableModel model = (DefaultTableModel) praticienTable.getModel();
                model.setRowCount(0);
                Show_Praticien_In_JTable();

                JOptionPane.showMessageDialog(null, "Données " + message + " avec Succès");
            } else {
                JOptionPane.showMessageDialog(null, "Données impossible à " + message, "Accès refusé", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    //Partie Selection par id
    /*
    public static Praticien selectOne(int id_praticien) throws SQLException {
        Praticien praticien = null;
        ResultSet rs;
        PreparedStatement pstmt;
        Connection connection = MysqlConnection.ConnectDB();
        
        // préparer la requête
        String query = "SELECT * FROM praticien WHERE nom= ?";
        pstmt = connection.prepareStatement(query);
        pstmt.setInt(1, id_praticien);
        rs = pstmt.executeQuery(query);
        if (rs.next()) {
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                String adresse = rs.getString("adresse");
                String ville = rs.getString("ville");
                String code_postal = rs.getString("code_postal");
                String telephone = rs.getString("telephone");
                String secteur = rs.getString("secteur");

                praticien = new Praticien(nom, prenom, adresse, ville, code_postal, telephone, secteur);
            
        }
        pstmt.close();
        pstmt = null;
        rs.close();
        rs = null;
        return praticien;
    }
     */
    //Partie ajout praticien
    /**
     *
     */
    public void Show_Combo1_Praticien() {
        try {
            Connection connection = MysqlConnection.ConnectDB();
            Statement st = connection.createStatement();
            String query = "SELECT * FROM praticien";
            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {
                String nomDesc = "Nom par ordre décroissant";
                String normal = "Affiche normal ";
                String DateDesc = "Date par ordre décroissant ";
                jComboBox1.addItem(nomDesc);
                jComboBox1.addItem(normal);
                jComboBox1.addItem(DateDesc);
                System.out.println(jComboBox1.getSelectedItem());

            }//end while
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /*
     public Praticien selectOneByName(String nom, String prenom) throws SQLException {
        Praticien unPraticien = null;
        ResultSet rs;
        PreparedStatement pstmt;
        Connection connection = MysqlConnection.ConnectDB();
        // préparer la requête
        String query = "SELECT * FROM praticien WHERE nom=? AND prenom= ?";
        pstmt = connection.prepareStatement(query);
        pstmt.setString(1, nom);
        jComboBox1.addItem(nom);
        pstmt.setString(2, prenom);
        rs = pstmt.executeQuery();
        if (rs.next()) {
            int id_praticien = rs.getInt("id_praticien");
            String adresse = rs.getString("adresse");
            String ville = rs.getString("ville");
            String code_postal = rs.getString("code_postal");
            String telephone = rs.getString("telephone");
            String secteur = rs.getString("secteur");
            
            unPraticien = new Praticien(id_praticien, nom, prenom, adresse, ville, code_postal, telephone, secteur);
        }
        pstmt.close();
        pstmt = null;
        rs.close();
        rs = null;
        return unPraticien;
     }
     */
 /*
    public static List<Praticien> selectAll() {
        List<Praticien> lesPraticiens = new ArrayList<Praticien>();
        Praticien praticien;
        ResultSet rs;
        try {
            PreparedStatement pstmt;
            Connection connection = MysqlConnection.ConnectDB();
            // préparer la requête
            String query = "SELECT * praticien";
            pstmt = connection.prepareStatement(query);
            rs = pstmt.executeQuery(query);
            while (rs.next()) {
                int id_praticien = rs.getInt("id_praticien");
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                String adresse = rs.getString("adresse");
                String ville = rs.getString("ville");
                String code_postal = rs.getString("code_postal");
                String telephone = rs.getString("telephone");
                String secteur = rs.getString("secteur");
                

                praticien = new Praticien(id_praticien, nom, prenom, adresse, ville, code_postal, telephone, secteur);
                lesPraticiens.add(praticien);
            }
            pstmt.close();
            rs.close();
        } catch (SQLException ex) {
            
        }
        return lesPraticiens;
    }
     */
 /*
    public void praticienSelectionne(){
        Praticien praticienSelect;
        praticienSelect = (Praticien) jComboBox1.getSelectedItem();
        
        jTextNum.setText(Integer.toString(praticienSelect.getId_praticien()));
        jTextNom.setText(praticienSelect.getNom());
        jTextPrenom.setText(praticienSelect.getPrenom());
        jTextAdresse.setText(praticienSelect.getAdresse());
        jTextVille.setText(praticienSelect.getVille());
        jTextCp.setText(praticienSelect.getCode_postal());
        jTextSecteur.setText(praticienSelect.getSecteur());
        jTextTel.setText(praticienSelect.getTelephone());
        
    }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjout;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonPrec;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable praticienTable;
    // End of variables declaration//GEN-END:variables
}
